# Generated by Django 4.2.5 on 2023-10-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNetflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
