# Generated by Django 4.2.5 on 2023-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNetflix', '0004_remove_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='AppNetflix/assets/img/peliculas/'),
        ),
    ]
