# Generated by Django 4.2.5 on 2023-10-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNetflix', '0006_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='default.jpg', upload_to='AppNetflix/assets/img/portadas/'),
        ),
        migrations.AddField(
            model_name='serie',
            name='portada',
            field=models.ImageField(default='default.jpg', upload_to='AppNetflix/assets/img/portadas/'),
        ),
    ]
